export const blogs = [
  {
    titles: [
      "Revenue Models & Sustainability",
      "Meadow’s Sustainability Plan",
      "Revenue Model",
      "Meadow Insurance Model",
      "Launch Strategy & Perks",
    ],
    texts: [
      "Meadow is a launchpad domiciled on the Sui blockchain. As a decentralized incubator, meadow offers various tools for blockchain innovators eyeing the Sui blockchain — especially for gaming projects.The Sui Blockchain is an offshoot of the Move programming language developed by Meta-backed project, Diem. A layer 1 of Ethereum and Avalanche’s caliber but with better unique features like high throughput and zero latency. Sui augmented the Move language to form what is called the Sui Move — an improvement on the laxities contained in the parent move language.",
      "To foster transparency in the meadow ecosystem, this piece will take a look at how Meadow plans on keeping its ecosystem’s economics functional and beneficial for both the host and builders.",
      "To generate revenue for the long run, meadow looks to deduct 1% fee for every trade that happens.This fees goes into the treasury and converted into stable coins that will be used to fund various endeavors, like: \n\nOn-boarding Team Members \nCollaborate With Prospective Partners \nBuilding and Marketing \nPaying Employees \nTo Improve Meadow’s Overall Brand \n\nScenario: \n\n$10,000,000 Total Volume = $100,000 Revenue​ \n\n$50,000,000 Total Volume = $500,000 Revenue \n\nMeadow is expected to generate $100,000 in revenue in the first month from this unique revenue source which equates to $10,000,000 in volume.",
      "If there’s one thing 2022 has taught every citizen of the cryptoverse: it is that the mighty can fall at a time when everyone least expects. Just like FTX, and its CEO, Sam Bankman-Fried. The crypto winter and the recent crypto catastrophes prompted the Meadow team to create an insurance model for every project launched on through its platform. \n\nEvery project that meadow grooms and launches will remit 5–10% of its total raise at IDO into the insurance pool. This will compound over time into a canopy pool where certain investors can get a fraction of their invested capital in case their project plummets. The insurance pool has different tiers: Diamond, Gold, Silver, Bronze.\n\nDiamond: When Meadow helps launch a project that is subscribed to the Diamond tier, the builders are entitled to 30% of their invested capital if things fall apart.\n\nGold: The Gold hierarchy presents 15% of invested capital if the project fails.\n\nSilver and Bronze: These tiers aren’t entitled to the insurance pool.",
      "We know Sui is one of the most superior networks, but Meadow will first launch on the BEP20 Network. Then we will bridge back to the Sui Network while the ecosystem grows. This is a more responsible approach. One of the main advantages is that the BEP20 Network processes on average three million transactions per day, showing its high throughput. This means that the Meadow token will be more accessible, putting our token at a huge advantage. Although Sui has been growing rapidly, we believe it is better to strategically plan everything for the first couple months and then launch. And when we launch on the Sui Network, we’ll be going multichain. In terms of when Meadow will do its Public IDO: it will be sometime in April — May time. This gives us enough time to plan everything out and make sure we are going in the right direction.\n\n",
    ],
  },
  {
    titles: [
      "Sui Blockchain: A Brief Look Into The Ecosystem",
      "The Sui Technology ",
      "Infrastructural Upsides Compared To Other Legacy Blockchains ",
      "Gaming Projects Are Swarming Sui",
      "Why You Should Join The Sui Ecosystem",
    ],
    texts: [
      "A few years ago, Facebook launched Libra. However, dynamics changed as the project wasn’t positively forthcoming. In an effort to crank out results, Libra changed to Diem; they shipped Novi (a crypto wallet, but Silvergate crypto bank bought it). Now, Diem is inoperative. However, they did launch some resilient assets: the move programming language, and the Move virtual machine.  \n \nFormer gatekeepers at Diem founded Mysten Labs. They utilized their work, at Diem, on the move programming language to build the Sui blockchain.  \n \nThe Sui blockchain is a trailblazing non-latent layer 1 protocol (like Ethereum, Bitcoin, Cardano, etc.) with massive throughput.  \n",
      "Mysten Labs—a web3 establishment with founders from the Meta-backed Novi Research at Diem—owns the Sui technology.  \n \nThe Sui ecosystem consists of three major working parts: Objects, Transactions, and Validators.  \n \nObjects: The Move language is object-oriented. Therefore, the Sui blockchain’s smart contracts are object-orientation enabled, which are controlled by move packages. These objects fall into Mutable Data Values and Immutable Packages classifications.  \n \nTransactions: this describes any iteration or improvement to the Sui ecosystem. Their execution modifies the Sui ledger. \n \nValidators: the Sui ecosystem is run and controlled by independent validators.  \n \n",
      "Speed: Sui uses a process dubbed as Transaction Parallelization to augment assets and increase Production. It processes throughput of around 160000 tps (transaction per second).  \nScalability: Compared to other OG blockchains, Sui eliminates latency to solve Web3-persistent problems like slow games, expensive DApps, loss of funds, overpriced asset floor prices, and stratospheric gas fees, etc.  \nSecurity: Assets are self custodial through auditable smart contracts. Plus a fault tolerant system if a validator acts maliciously.  \n",
      "Sui blockchain is described as the best suited destination for gaming projects that are keen on improving the crypto gaming ecosystem. When a blockchain is run by an avant garde language like Move, which allows programmable objects, it attracts the attention of gamers.  \n",
      "Builders and innovators have been easily boarding the Sui ecosystem train. Why? The Sui ecosystem comes with a customized user experience navigator in its SDK (Software Development Kit). Porting from other ecosystems hasn’t been easier.  \n",
    ],
  },
  {
    titles: ["Meadow: Ultimate Sui Launchpad ", "The New Promising Launchpad"],
    texts: [
      "For starters, in the traditional finance world, raising money for your idea or project can be quite discouraging. The first hurdle is convincing willing investors that the project is revolutionary or disruptive; and the second is getting the capital paid in a seamless manner. Another problem is investors playing an oversight and imposing unfounded, unrealistic policies on the founders in a bid to recoup their money back.  \n \nHowever, the DeFi (Decentralized Finance) sector of the crypto-verse is doing things differently. For a nascent space, the dynamics are quite confusing. Crypto launchpads or IDOs (Initial DEX offerings) are platforms that allow projects to raise money; and, analogously, allows investors to invest in early stage projects at a cheaper price. A win-win for both parties.  \n \nLaunchpads offer more. Not only are they a money raiser, they help vet projects, train founders (if need be) and offer their expertise and experience as though they were part of the team. This blocks all loopholes a project may have, and also groom the founders to understand the space they’re trying to dominate.  \n",
      "Meadow is a launchpad on the Sui blockchain. Not only is meadow a crowdfunding space for new projects, the founding team is a group of crypto veterans who understand the art of improving projects and helping founders skyrocket their project’s value and reach.  \n \nMeadow beats other Sui launchpads, and even other IDOs on other blockchains, with its IGO (Initial Game Offering). It’s as a result of the kind of project Meadow attracts, a consequence of its domicile blockchain (Sui blockchain). The Sui blockchain, because of its object-oriented language, best suits Gamers.  \n \nHowever, the nature of the blockchain doesn’t limit it to Gaming projects: it extends to all blockchain use cases. Therefore, Meadow isn’t only a Gaming launchpad but all crypto projects launchpad.  \n \nJoin Meadow to crowdfund for your project and also vet and improve it. \n",
    ],
  },
  {
    titles: [
      "The Benefits of The Sui Blockchain and its integration with Meadow: A New Era In DeFi  ",
      "Meadow: A Big Sui Player",
    ],
    texts: [
      "\nFormer Meta employees decided to build another groundbreaking blockchain that will tackle the persistent Blockchain Trilemma that has beset legacy blockchains since the advent of distributed data systems. Their ambition and dedication birthed Sui, a layer 1 blockchain that employs the Sui Move programming language in structuring its foundation and its smart contracts.  \n \nBefore Sui, many blockchain experts had opined that the achievability of Scalability, Security, and Speed is close to impossible. They said one feature would, inevitably, be sacrificed for the other. But Sui’s architecture provides an infrastructure that allows no latency, has high throughput, and immense security. An unprecedented feat.  \n",
      "The blockchain thrives on ecosystem dynamics. The more projects build and launch on a blockchain, the better its strength in terms of security. The Sui blockchain ecosystem is skyrocketing. However, for builders, navigating a new blockchain can be a slippery path, which is where crypto incubators come alive.  \n \nMeadow is an incubator for projects utilizing the Sui blockchain. Meadow offers support for builders in terms of generating funds for keeping the project alive, helping founders settle on their new found domain, and building the project’s infrastructure to be the best.  \n \nIf you’re a project founder in gaming, DeFi, the crypto-verse (in general), and you’re eyeing the Sui blockchain to launch and develop your project: Meadow is the best place to start.  \n \nCome onboard the meadow ship to enjoy a smooth Sui sail.  \n",
    ],
  },
  {
    titles: [
      "Integrating Meadow and Sui Blockchain: The Inherent Benefits For Entrepreneurs Building In the Bear Market",
      "The Need For The Confluence",
      "How To Benefit As An Entrepreneur Or An Investor",
    ],
    texts: [
      "Sui blockchain, as discussed in previous articles, is a state-of-the-art blockchain that tackles various problems that legacy blockchains failed at. Problems like speed, throughput, and scalability are now solved using Sui blockchain’s parallel execution infrastructure.  \n \nSui employs Move, another programming language which outdoes the likes of Solidity, Haskell, in terms object oriented smart contract building.  \n \nAnd in the Sui ecosystem is Meadow: a crypto incubator that gets crypto entrepreneurs accustomed to the Sui blockchain and ecosystem (at large).  \n",
      "The Meadow team chose a new and growing ecosystem to build something on. However, the choice didn’t stem from being opportunistic but from an ethical position. The meadow is looking to bolster the development of the crypto-verse, and make it more robust.  \n \nThis is why Meadow is a place for any crypto project—gaming projects, especially—that chooses the Sui Blockchain as its domicile.  \n \nSui solves traditional blockchain problems. Meadow solves blockchain’s social problems.  \n",
      "Entrepreneurs building projects in this crypto winter need a low-bar entry in securing funds to keep their projects running. Meadow is a launchpad that helps projects source for funds, and they also become advisors to every onboarded project.  \n \nFunding an early project is cheaper than a fully grown one. Investors who are just starting out or even seasoned investors looking for projects that are in their early days, Meadow is the best place to be. The availability of funding vetted, and trusted projects at a cheap price makes it a worthy investment platform.  \n \nSui is fast growing. And, consequently, Meadow is growing rapidly, too. Being an early bird is a bragging right and an endeavor with future massive returns.  \n \nJoin the Meadow ecosystem today. \n",
    ],
  },
  {
    titles: [
      "Exploring Some Of Meadow’s Partnerships",
      "Sui Community ",
      "Vital Block (VB) Audit",
      "Read2N",
      "EthosWallet",
      "Read2N",
    ],
    texts: [
      "We’re not lone rangers at Meadow. We believe that our vision of expanding crypto, its offerings, and further its use cases require some healthy partnerships. Collaborations with same minded establishments and projects to help promote the effectiveness of the Sui blockchain; then, bolster the ecosystem, generally.  \n",
      "The Sui community is a gathering of Sui blockchain believers and enthusiasts who are either actively participating (by building on Sui or spreading its good news) or looking to take advantage as an early investor. The Sui community gets updated with the latest news and trends about the Sui Blockchain.  \n \nMeadow and Sui Community’s partnership will foster the advancement of the Sui blockchain and Meadow’s incubator, moving forward, as Meadow enthusiasts get firsthand news and information about our inventories.  \n",
      "The crypto space is known for various catastrophes. We’ve seen projects with little to zero credibility come with various scams, system glitches, etc. So in a bid to assure every Meadow believer of their financial and identity safety, we partnered with VB Audits to affirm our team, project’s legitimacy, and further bolster our community’s trust in us through transparency.  \n \nVB Audits is a Smart Contract auditing company for blockchain projects.  \n",
      "\nRead2N is a content (copyright governance NFT) distribution platform that’s looking to launch on the Sui blockchain network. It comes with Game-Fi and Social-Fi components as a web3 lifestyle application. It’s the first enterprise that allows people to build on their daily affairs like reading, and also earn.  \n \nPartnering with Meadow brings different perspectives to how people view the Sui ecosystem as it becomes richer and more robust.  \n",
      "Ethos Wallet prides itself as the “Home base for Web3 on Sui Blockchain.” Ethos Wallet is the leading decentralized app on the Sui network. It can save and trade crypto; also, it can discover and build apps on the Sui network. \n \nOur partnership means we’ll be integrating Ethos Wallet on our Launchpad to further strengthen both our offerings and, extensively, the Sui blockchain.   \n \n \nAt Meadow, we’re choosing promising partners to help boost each other’s reach and the ecosystem’s strength for the benefit of our believers and the crypto-verse.  \n \nJoin Meadow today, as we further explore more of our partnerships and the embedded benefits of the collaborations.  \n",
    ],
  },
  {
    titles: [
      "Meadow Incubator: What Prospective Builders Need To Know",
      "You Need To Build Now",
      "Meadow’s Part",
    ],
    texts: [
      "Meadow is currently expanding its social media presence through various campaign programs. As we’re seeking to reach more people who want to help build the Sui ecosystem, we thought we’d clarify our offerings by showing what we are doing exactly.  \n \nThe 2017 crypto bull run made us believe the crypto space is a replica of the traditional tech startup universe. However, many projects withered when trying times came. Why? They were not truly vetted and built from scratch. They lacked substance. And since then, the crypto ecosystem has become wiser.  \n \nOur incubator program, as discussed online in various articles, social media posts, and community discussions, is the most visible.  \n \nWe help build and launch various projects that want to build on the Sui blockchain by providing funding (sourcing through our large—and rapidly increasing—community), advisory support and experience, technical expertise (if needed), and fool-proof insurance program to prepare contingencies. We are striking various agreements and partnerships to further strengthen our authority as one of Sui Blockchain’s pacesetters.  \n",
      "Although, there has been some upward movement in the crypto charts lately yet it’s common knowledge that the crypto winter isn’t over. Any project that builds, and sails through this windy times, has credibility for solid infrastructure and backing.  \n \nMoreover, building during crypto bear runs has another upside: the bull run profits. After having gone the rickety road of a harsh market, a booming market is a compensation. \n",
      "In the traditional startup space, investors are tepid about writing checks during economic downturns. However, crypto founders looking to garner funds to birth their idea, build a team, and scale, don’t have to go through the hassle of pitching to thousands of investors.  \n \nThe Meadow community, for the Sui ecosystem, caters for all financial helps that accepted founders need.  \n",
    ],
  },
  {
    titles: ["Meadow’s Incubatory Benefits Explained"],
    texts: [
      "Meadow’s incubator is built to help founders navigate the terrains of the Sui blockchain ecosystem without hassle. Sailing uncharted waters can be hectic but Meadow has mapped out the journey for every founder looking to build on the Sui ecosystem.  \n \nWe’ve built a roadmap for our incubation processes and it’s on the meadow website. However, we’re highlighting the benefits for choosing Meadow incubator to propel into the Sui ecosystem.  \n \n \n \n \nWe have direct affiliations to various renowned CEXs that we can get you listed on for free \nor paltry prices. This will save a ton of resources, hassle and funds.   \n \n- We have a bank of 200+ Influencers ready to shill your project across socials.  Our stack of influencers have high credibility, ensuring you get the best marketing for your project. \n \nOur connections are your connections; we help garner additional funds to help keep your project afloat.  \n \n \n- Our partnership includes long term advisory benefits for your project. Getting in touch with people—big names, especially—can be frustrating but our widespread network can do that in no time.  \n \n- Exposure to media channels is important. We can get your content uploaded on numerous news channels that get millions of visits ensuring you get the absolute best prices, at a fast pace.  \n \n- Connection to notable content creators is also a perk; we excel at that.  \n",
    ],
  },
  {
    titles: ["How Meadow Transcends Traditional Incubators"],
    texts: [
      "Incubators basically support early stage businesses to help increase their chances of surviving, scaling, and profitability.  \n \nHowever, one of the shortcomings of incubators—before remote work became commonplace—was they equated real estate to incubation. They ignored project content and offering, and went big on cheap workspaces and commodity services. These are all cheap because it’s easy to give out free workspaces and subsidized accounting or legal services, but hectic to groom and grow a business.  \n \nOf course, the world is now in a remote working era yet Meadow will groom various projects program content with candor, coupled with fundraising that’s required to keep team members motivated and project running. We’ll tackle the basics of growing a crypto project; then go up from there. We look past fundraising as a metric to determine the prospect of any project.  \n \n \nWe know various spots where projects get inundated and stuck, and we’ve provided every resource needed to hurdle those obstacles. From connections to all other supplies that’s required to scale web3 ideas, any project looking to launch on the Sui ecosystem can rest assured that meadow has their back.  \n",
    ],
  },
  {
    titles: ["Meadow Incubator Tier Systems"],
    texts: [
      "Crypto Incubator tier systems are levels of investing participatory access, which comes with certain privileges that investors in a particular incubator community have in that community domain.  \nWe’ve assessed many tier systems at other launchpads and we came to a conclusion that these launchpads have stratospheric barrier entry with minimal compensations for lower tiers. This makes it technically decentralized as people with the biggest bags are the most favored.  \n \nWe reorganized the tier system, with a low entry barrier, such that investors get their tier’s worth in accurate compensation. This implies that the higher the tier, the better the benefits.  \n \nMeadow built four tiers with different entry levels and benefits:  \n \nDiamond (Best) - 50,000 tokens \nGold - 25,000 tokens \nSilver - 15,000 tokens \nBronze (Lowest tier) - 5,000 tokens \n \nTo receive allocations, the Diamond tier is free of any upgrading tasks while other tiers require some tasks to be completed (Owning a twitter account is required as some of the tasks are conducted on Twitter).  \n \nAs more investors stake the ecosystem’s native tokens, the TVL (Total Value Locked) of the launchpad begins to increase; consequently, the intrinsic value of the particular token increases. A win-win situation for the investors, ecosystem, native blockchain, and—generally—the crypto-verse.  \n",
    ],
  },
  {
    titles: [
      "Meadow Incubator Tier Systems",
      "Blockchain And AI",
      "Meadow And Artificial Intelligence ",
    ],
    texts: [
      "Crypto Incubator tier systems are levels of investing participatory access, which comes with certain privileges that investors in a particular incubator community have in that community domain.  \nWe’ve assessed many tier systems at other launchpads and we came to a conclusion that these launchpads have stratospheric barrier entry with minimal compensations for lower tiers. This makes it technically decentralized as people with the biggest bags are the most favored.  \n \nWe reorganized the tier system, with a low entry barrier, such that investors get their tier’s worth in accurate compensation. This implies that the higher the tier, the better the benefits.  \n \nMeadow built four tiers with different entry levels and benefits:  \n \nDiamond (Best) - 50,000 tokens \nGold - 25,000 tokens \nSilver - 15,000 tokens \nBronze (Lowest tier) - 5,000 tokens \n \nTo receive allocations, the Diamond tier is free of any upgrading tasks while other tiers require some tasks to be completed (Owning a twitter account is required as some of the tasks are conducted on Twitter).  \n \nAs more investors stake the ecosystem’s native tokens, the TVL (Total Value Locked) of the launchpad begins to increase; consequently, the intrinsic value of the particular token increases. A win-win situation for the investors, ecosystem, native blockchain, and—generally—the crypto-verse.  \n",
      "Artificial Intelligence has come a long way since its proposition in the 1950s. The idea of Machine Learning (a concept of how computer algorithms can learn from data other than a set of mapped out rules) brought a drastic change into the AI landscape. It grew faster and improvements happened quicker as AI now has a larger well of data to draw from.  \n \nNow, we’re currently in the Big Tech AI war era. Google and Microsoft are dueling to see who wins the AI race. Microsoft, being a big investor in OpenAI, had an upper hand in collaborating with OpenAI to bring ChatGPT (a groundbreaking intelligence never seen before since the inception of the idea in the 50s) to Bing (Microsoft’s search engine).  \n \nChatGPT is the current center of attention in the tech world because of its conversational nature and the tasks it can perform: write articles, code, answer questions—that’d normally take hours of Google-searching—in one page with lots of relevant data and detailed explanation. Its large search range, power, and exposition spurred the tech behemoths into the AI war as they looked to augment their search engines with AI.  \n \nThe AI business is booming and it’s quite complicated to make a forecast of its worth in the next 5 years. But, in 2019, MarketsAndMarkets predicted that the AI industry (worth around USD 9 billion at the time) can be worth USD 190 billion by the year 2025. Last year, the AI industry was worth USD 86.9 billion at a CAGR (compound annual growth rate) of 36.2%, which goes to show the MarketsAndMarkets predicted trajectory is valid and that it’s on a course to happen. In fact, the current AI battle in the big tech space is a gigantic booster.  \n",
      "Although they are both separate technological epiphanies from different times, the potentials of merging these two powerful technologies can be massive.  \n \nOne of the problems that has plagued the blockchain world is scalability. However, AI possesses the ability to sift through, sort, and analyze large data. Crypto transactions produce enormous data, and dealing with these data causes high latency. Some blockchains today are hurdling this particular problem e.g. Sui Blockchian but AI can help overcome this malady for life.  \n \nAnother way AI can influence blockchain is security. Humans have written endless lines of codes to improve the blockchain financial domain and ward off attackers but they still keep coming in their numbers. We’ve seen various scams and hacks on different crypto services and companies in the past years. AI can help discover malicious intent on a network and act swiftly before the attackers can do damage.  \n \nAI can help improve Smart Contracts to further solidify the “trustless” mantra of the blockchain-verse. AI can be used to implement agreements put into smart contracts, which improves the transaction’s speed and efficiency \n",
      "At Meadow, we see the value that AI brings to crypto and blockchain at large. This is why we’ll have a section for AI projects looking to launch on the Sui ecosystem. Moreover, we are also looking to augment and improve our own ecosystem by integrating meadow launchpad with AI.",
    ],
  },
  {
    titles: [
      "Sui And Aptos Blockchains: A Brief Overview",
      "Can Sui Overtake Aptos? ",
    ],
    texts: [
      "Sui and Aptos blockchains are daughter blockchains born from the exodus of blockchain experts from Diem (the defunct Meta project). Like we’ve mentioned in preceding articles, one of the groundbreaking inventions by the Diem team is the Move language. Move essentially is a programming language, in the class of solidity and haskell, that can be used to build a smart contract for blockchain projects. Mysten Labs built the Sui blockchain while Aptos blockchain comes from Aptos Labs: a bifurcation of former Meta engineers. Sui and Aptos are both layer 1 blockchains in the stratum of Ethereum, Cardano, etc. with similar infrastructure as they both execute transactions in parallel. However, Since their founding dates are a year apart (Sui 2022, Aptos 2021), Aptos has achieved higher scalability and improvement over time. Sui executes 120, 000 transactions per seconds (TPS) while Aptos has upped its TPS to around 160, 000. ",
      "Although  Sui’s \nit’s Move \na variant \ndifficult gives \nprediction, the \nSui definite \nshows state \nmore of \nprospects object: \nwhen Is \nit it \ncomes owned/shared \nto or \ndevelopment mutable/immutable? \nand while \nmore Aptos \nroom doesn’t. \nfor Subtle \nimprovement. advantages \nAptos like \nhas these \noptimized place \nits Sui \ndesign at \nto a \nbe vantage \ndurable point \nbut to \nSui overtake \nshows Aptos \nrange as \nwhen time \nit goes \ncomes on. \nto \nproject \nbuilding \nand \nsupport. \n",
    ],
  },
];
