import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import Nav from "./../components/Nav";
import Main from "./../components/Main";

export default function Home() {
  return (
    <div className='h-screen w-full pt-[70px] md:pt-0 bg-white-1 flex items-center relative overflow-x-hidden  '>
      

      <img src={"/object-2.svg"}  className='absolute lg:left-[837px] left-[130px] -top-[10px]  lg:-top-[95px] w-[261.73] h-[261.73px] bg-image-2   ' alt="small object" />
      
      <div className='lg:h-[947.31px]   md:p-[11px] w-full flex md:max-w-[1440px]  pr-0 overflow-hidden md:space-x-[62px] mx-auto my-auto '>
        <Head>
          <title>Meadow</title>
          <meta name='description' content='Generated by create next app' />
          <meta name='viewport' content='width=device-width, initial-scale=1' />
          <link rel='icon' href='/logo-card.svg' />
        </Head>
        <Nav />
        <Main />
      </div>
    </div>
  );
}
